### ISSUE TITLE
Please update for VS 2013 update 4, update for 2015. Update base16

### ISSUE THREAD

**Issue by ghost** [brettof86/base16-visual-studio#1]

**Comment by blockloop** [comment]
Updated to the latest version as of today. I didn't like VS 2013 so I went back to 2012. Tell me if that fixes your issues. 3fbd3dfee98d40ce5c4e65f1b33a66f0f8c06441

**Comment by ghost** [comment]
Thank you, is there any updates to Base16.Tomorrow?

**Comment by ot-brett-jones** [comment]
I don't see any changes to that file in the commit. I re-ran it with every template so it would have updated in the commit. It looks like the only difference was additional themes and base16-default had some changes.

**Comment by blockloop** [comment]
I don't see any changes to that file in the commit. I re-ran it with every template so it would have updated in the commit. It looks like the only difference was additional themes and base16-default had some changes.

**Comment by ghost** [comment]
Thanks, maybe I will update the vs template, I'm sure R# added more colors and VS13 did.
